### ISSUE TITLE
Next Sync of Rolling Branch With Humble Branch

### ISSUE THREAD

**Issue by swiz23** [ros2/rcpputils#173]
Hi,

Just was curious if there is a plan to sync up the 'humble' branch with changes done in the 'rolling' branch. There is a 3rd party package (ros2_controllers - https://github.com/ros-controls/ros2_controllers/pull/477) that changed some of its includes to 'rccputils' from 'rcppmath' (deprecated in commit 1bd32c72b355761b11dd9e35abe4d2cc32b7187a), so now the main ros2_controllers branch doesn't compile in humble.

**Comment by clalancette** [comment]
So we don't typically sync Rolling into Humble.  The idea with Rolling is that we can make breaking changes there, and it won't effect the API/ABI of the stable distributions.

In this case, you have a couple of options:

1.  Use a separate branch in ros2-controls for Rolling and Humble.  This is what we do in the core, and it allows us to absorb these breaking changes.  The downside is that if you really want to keep the two branches in sync, you have to do that by hand (though we do have a bot that helps us with this).
2. Use the ROS_DISTRO environment variable.  That is, in your CMakeLists.txt, detect what ROS version it is by looking at the ROS_DISTRO environment variable, and then add defines that you can switch on in the code based on this.  You can see an example of doing something like that in https://github.com/tilk/rtcm_msgs/blob/master/CMakeLists.txt

Since this isn't something we are likely to do, I'm going to close this out.  But please feel free to keep commenting.

**Comment by swiz23** [comment]
Understood. Thanks!
