### ISSUE TITLE
Create a utility function that wraps assert but instead throws

### ISSUE THREAD

**Issue by piraka9011** [ros2/rcpputils#29]
Inspired by [Kotlin's Assert](https://www.bignerdranch.com/blog/write-better-code-using-kotlins-require-check-and-assert/), it would be helpful to have a wrapper around assert that instead throws to provide a meaningful stack trace.

**Comment by emersonknapp** [comment]
Do you mean a wrapper around assert? Or do you mean an assert-like functionality that works in non-debug builds?

**Comment by zmichaels11** [comment]
I think it would be better as `assert-like`

**Comment by tfoote** [comment]
Please consider picking up https://github.com/ros2/rcutils/pull/112 that got deprioritized previously.

**Comment by zmichaels11** [comment]
Possible implementation: https://github.com/ros2/rcpputils/pull/31

**Comment by wjwwood** [comment]
What is the benefit of having an assert that throws over the standard one that uses abort? Doesn't gdb break on abort just like it does with an exception? Or were you thinking of catching the exceptions? I'm just trying to understand the motivation.

I do understand a `require` or `check` that always asserts even when in release mode.

**Comment by wjwwood** [comment]
> Please consider picking up ros2/rcutils#112 that got deprioritized previously.

This could be a good solution, but note that this implementation is a bit different, as in the case that the condition fails it logs to the rcutils logger (which may or may not be desired) and it uses a "DebugBreak" which is a trap, rather than throwing an exception (which it cannot do since it might be used in C only code) and rather than using `abort()` which on Linux would result in a `SIGABRT` (I think).

If the main goal is to have an `assert()` that works in release mode too (a.k.a. `check` or `required`) then ros2/rcutils#112 might be overkill.

**Comment by zmichaels11** [comment]
A benefit of throwing vs abort is that failure can be checked in unit tests.

**Comment by wjwwood** [comment]
I see, Google Test has "Death tests" which work with asserts but I guess they're hard to use and sometimes don't work as expected on Windows:

https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#how-to-write-a-death-test

**Comment by zmichaels11** [comment]
Also, an exception carries the additional information that the code crashed due to a `check`, `require`, or `assert`

**Comment by wjwwood** [comment]
> Also, an exception carries the additional information that the code crashed due to a check, require, or assert

You mean in gdb? You should be able to see the same kind of information as with an unhandled exception, but I haven't compared the two closely.

The "debugbreak" style proposed in https://github.com/ros2/rcutils/pull/112 might be preferable since it can be called from and across pure C99 layers too. Though I guess those cannot be as easily caught in tests as the exceptions.

**Comment by zmichaels11** [comment]
No, I meant in tests.

**Comment by wjwwood** [comment]
I see what you mean.

**Comment by zmichaels11** [comment]
I'm thinking it can be improved by introducing an `AssertionException` that way in tests, you can `EXPECT_THROWS` on the `AssertionException` and know that your code is properly failing

**Comment by emersonknapp** [comment]
Issue closed in https://github.com/ros2/rcpputils/pull/31
