### ISSUE TITLE
Is there any reason to only search for libraries in `LD_LIBRARY_PATH`?

### ISSUE THREAD

**Issue by mayuso** [ros2/rcpputils#34]
I am trying to create a compiled package to be used in machines without ROS2 installed. I basically have my executable, and a `lib/` directory with all the necessary libraries it needs.

This solution works perfectly when adding my `lib` directory to `LD_LIBRARY_PATH` in the new machine before calling the executable, but it fails if I call it as root (Calling `sudo` clears `LD_LIBRARY_PATH`), which is needed, for example, to handle thread priorities.

Is there any reason to have `LD_LIBRARY_PATH` as the only place to look for libraries? Could we add more common search paths like `.`, `./libs` or `./lib` or would it be a problem for some reason that goes over my head?

**Comment by zmichaels11** [comment]
Hi,
I don't think this is the correct location for this issue since `rcpputils` is a package in `ros2` while it sounds like you are asking a general Linux question or a ROS2 usage question.

I believe "`sudo` clears `LD_LIBRARY_PATH`" is a feature of `sudo` since it makes sense for `LD_LIBRARY_PATH` to be different for different users. You could probably find a better answer to this part of the question on https://stackoverflow.com/

If what you want to do is run a `ROS2` node without installing dependencies through apt, you might find success in building from source up to the required package and sourcing the workspace on your target machine. You can find instructions on building from source [here](https://index.ros.org/doc/ros2/Installation/Dashing/#building-from-source)
