### ISSUE TITLE
Need for std::filesystem::remove_all equivalent

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rcpputils#62]
At least on windows, the `remove()` function fails when the to be deleted directory is non empty.
This requires sort of a recursive deletion as used within rosbag2: https://github.com/ros2/rosbag2/blob/c28c89267fa8e22e76c6540ffb700f908eca04db/rosbag2_test_common/include/rosbag2_test_common/temporary_directory_fixture.hpp#L59-L99

**Comment by hidmic** [comment]
That behavior is consistent with [`std::filesystem::remove`](https://en.cppreference.com/w/cpp/filesystem/remove) for C++17 onwards, so I think that's expected and intended. Maybe you're looking for a [`std::filesystem_helper::remove_all`](https://en.cppreference.com/w/cpp/filesystem/remove_all) equivalent, which does not exist (yet).

**Comment by mjcarroll** [comment]
It's because `std::filesystem::remove` (I believe) maps to the posix [`remove`](https://pubs.opengroup.org/onlinepubs/000095399/functions/remove.html) call, which ultimately calls [`rmdir`](https://pubs.opengroup.org/onlinepubs/000095399/functions/rmdir.html) on a directory.

`rmdir` fails when the directoy isn't empty.

**Comment by mjcarroll** [comment]
I would be in favor of adding a `remove_all` equivalent, especially since it's in the standard now.

**Comment by hidmic** [comment]
@Karsten1987 mind to update this issue description or close it in favor of a feature request for a  `remove_all` equivalent?
